$.lang = {};

$.lang.ko = {
    menu_1:'컬렉션',
    menu_2:'마켓플레이스',
    menu_3:'히스토리',
    menu_4:'로그인',
    menu_5:'마이 페이지',
    menu_6:'공지사항',
    menu_7:'NFT 생성',
    join_1: '등록 가능한 이메일입니다.',
    join_2: '이미 등록된 이메일입니다.',
    code_send: '인증 코드를 발송하였습니다.',
    code_fail: '인증 코드 발송에 실패하였습니다.',
    code_success: '이메일 인증에 성공하였습니다.',
    code_failed: '이메일 인증에 실패하였습니다.',
    chk_price: '판매 비용을 확인해 주세요.',
    sign_1:'ORDALABS NFT',
    sign_2:'이메일 주소',
    sign_3:'비밀번호',
    sign_4:'로그인',
    sign_5:'회원가입',
    sign_6:'비밀번호를 잊으셨나요?',
    register_1:'이메일',
    register_2:'인증하기',
    register_3:'비밀번호',
    register_4:'비밀번호 재확인',
    register_5:'가입하기',
    register_6:'로그인',
    register_7:'인증번호 확인',
    register_8:'확인',
    register_9:'새 비밀번호',
    register_10:'인증하기',
    register_11:'이메일 인증이 완료되면 비밀번호를 재설정할 수 있습니다. 이메일 인증을 진행해 주세요.',
    register_12:'비밀번호 변경',
    register_13:'가입되지 않은 이메일입니다.',
    register_14:'비밀번호 재설정에 성공하였습니다.',
    register_15:'비밀번호 재설정에 실패하였습니다.',
    search_0:'검색',
    search_1:'검색 결과',
    search_2:'아이템',
    search_3:'사용자',
    search_4:'컬렉션',
    my_0:'소유 작품',
    my_1:'즐겨찾기',
    my_2:'입찰 작품',
    my_3:'발행자',
    my_4:'판매 중',
    my_5:'판매하기',
    my_6:'낙찰품',
    my_7:'일일 보상 수량',
    my_8:'남은 보상 기간',
    my_9:'보상 없음',
    my_10:'일',
    my_11:'보상 지급 기간',
    my_12:'제안 작품',

    my_13:'제안 ON',
    my_14:'제안 OFF',
    my_15:'제안 받음',
    my_16:'제안함',
    my_17:'제안자',
    my_18:'소유자',
    my_19:'제안 가격',
    my_20:'거절',
    my_21:'승인',
    my_22:'승인 대기중',
    my_23:'구매 실패',
    my_24:'발행 작품',
    my_25:'판매 승인 중',
    my_26:'판매 취소',
    my_27:'판매 반려',

    cre_1:'아이템 생성',
    cre_2:'실제 NFT를 발행하기 전에 아이템을 생성하는 과정입니다.<br>생성된 아이템은 마이페이지에 표시되며, 관리자의 승인 후 NFT를 발행할 수 있습니다.<br>NFT 생성 과정에서는 이더리움 가스 비용은 발생하지 않습니다.',
    cre_3:'# NFT 썸네일',
    cre_4:'JPG, PNG, GIF 10MB 이하',
    cre_5:'# NFT 콘텐츠 파일',
    cre_6:'*jpg, png, gif, mp4, glb 100MB 이하',
    cre_7:'# 판매 로열티',
    cre_8:'태그',
    cre_9:'카테고리',
    cre_10:'NFT 생성하기',
    cre_11:'참고: 항목을 만드는 데 몇분이 소요될 수 있습니다. 업로드하는 동안 기다려 주십시오.',
    cre_12:'새로운 NFT를 미리 보려면 파일을 업로드하세요.',
    cre_13:'판매 타입',
    cre_14:'시작일자',
    cre_15:'종료일자',

    profile_1:'팔로잉',
    profile_2:'팔로워',
    profile_3:'가입',
    profile_4:'프로필 편집',
    profile_5:'로그아웃',
    profile_6:'출금 신청',
    edit_0:'프로필 이미지',
    edit_1:'등록하기',
    edit_2:'이름',
    edit_3:'소개',
    edit_4:'웹사이트',
    edit_5:'트위터',
    edit_6:'인스타그램',
    edit_7:'유튜브',
    edit_8:'닫기',
    edit_9:'저장',
    nft_list:'NFT로 판매할 아이템 보기',
    nft_price:'판매가',
    nft_edit:'발행할 에디션 수',
    nft_fee:'최초발행자 로열티 수수료',
    nft_0:'제목',
    nft_1:'상세설명',
    nft_2:'',
    nft_3:'수수료',
    nft_4:'서비스 수수료',
    nft_5:'아이템이 판매될 때 판매 가격의 서비스 수수료만큼 공제됩니다.',
    nft_6:'이 과정은 위의 아이템을 NFT로 발행하고 ORDALABS 마켓플레이스에 등록하는 것입니다. 아이템의 메타 데이터는 블록 체인에 저장되며 이더리움 가스피가 부과 될 수 있습니다.',
    nft_7:'NFT 등록(재판매)',
    nft_9:'NFT 등록(제안)',
    nft_8:'참고: 아이템을 등록하는 데 몇분이 소요될 수 있습니다. 조금만 기다려 주세요. ',
    ac_title:'사이트 거래현황',
    ac_desc:'이 페이지는 ORDALABS 사이트에서 일어나는 모든 아이템 등록, 판매 및 구매 현황을 보여줍니다.',
    ac_sale:'판매',
    ac_offer:'제안',
    ac_mins:'10분 전',
    ac_list:'등록',
    ac_withdraw:'전송',
    art_admin:'발행자',
    art_type:'판매 유형',
    art_remain:'남은 수량',
    art_1:'경매',
    art_2:'경매 종료',
    art_3:'일',
    art_4:'시',
    art_5:'분',
    art_6:'현재 가격',
    art_7:'입찰하기',
    art_8:'순위',
    art_9:'이름',
    art_10:'입찰 가격',
    art_11:'시간',
    art_12:'입찰 없음',
    art_13:'재판매',
    art_14:'입찰 현황',
    art_15:'고정가 판매',
    art_16:'구매하기(경매)',
    art_17:'구매하기',
    art_18:'초',
    art_19:'현재 입찰 가격',
    ac_own:'소유자',
    ac_total:'총 발행',
    ac_views:'조회수',
    ac_fave:'즐겨찾기',
    md_0:'유형',
    md_1:'발행자',
    md_2:'원래 가격',
    md_3:'IPFS에서 보기',
    md_4:'IPFS 메타데이터 보기',
    md_5:'마켓플레이스 아이템',
    md_6:'번호',
    md_7:'소유자',
    md_8:'마지막 판매 가격',
    md_9:'마지막 판매 시간',
    md_10:'정가',
    md_11:'거래 없음',
    md_12:'이더스캔 보기',
    md_13:'거래내역 현황',
    md_14:'거래 내역',
    md_15:'내 아이템',
    md_16:'구매하기',
    md_17:'품절',
    md_18:'미판매',
    md_19:'아이템',
    md_20:'제안하기',
    md_21:'구매(제안)',
    md_more:'더보기',
    md_more_item:'더 많은 아이템',
    md_collection:'컬렉션',

    pro_0:'언팔로우',
    pro_1:'팔로우',
    pro_2:'팔로잉',
    pro_3:'팔로워',
    pro_4:'가입',
    pro_5:'소유 작품',
    pro_6:'작품이 없습니다.',
    ad_buy:'최종 낙찰되었습니다. 24시간 이내에 구매 버튼을 눌러 구매해 주세요. 24시간 이내에 구매하지 않을 시 경매 참가가 제한됩니다.',
    ad_low:'최고 입찰가보다 낮은 입찰가입니다.',
    chk_sign:'로그인 후 이용해 주세요.',
    bid_1:'입찰가를 입력해 주세요.',
    bid_2:'입찰에 성공했습니다.',
    bid_3:'현재 입찰가보다 낮습니다.',
    bid_4:'입찰에 실패했습니다.',
    bid_5:'보유 중인 가상자산 내에서 입찰해 주세요.',
    offer_1:'보유 중인 가상자산 내에서 제안해 주세요.',
    offer_2:'제안에 성공하였습니다.',
    offer_3:'제안에 실패하였습니다.',
    offer_4:'제안가를 입력해 주세요.',
    offer_5:'제안가 받기 등록에 성공하였습니다.',
    offer_6:'이미 동일한 작품이 판매 중이라 제안가 받기가 불가합니다.',
    offer_7:'제안 거절하기를 성공하였습니다.',
    offer_8:'이미 제안한 가격이 있습니다. 거절 시 다시 제안 가능합니다.',





    chk_email:'이메일을 확인해 주세요.',
    chk_drops:'신규 작품을 받아보시겠습니까?',
    chk_sub:'구독 신청이 완료 되었습니다.',
    chk_price:'판매 가격을 확인해 주세요.',

    main_live:'실시간 NFT 경매',
    main_recent:'최근 등록 상품',
    main_idx_1:'ORDALABS NFT 아이템의 독점적인 발행 목록을 구독하고 새로운 등록 아이템에 대해 가장 먼저 알 수 있습니다.',
    main_idx_2:'인기 작품들',
    main_idx_3:'마켓플레이스 둘러보기',
    main_idx_4:'증강현실(AR) 기반 마켓플레이스 ORDALABS',
    main_idx_5:'ORDALABS은 디지털 아이템을 진정으로 소유할 수 있는 프리미엄 마켓플레이스입니다. 그리고 이 디지털 아이템은 언제 어디서나 증강현실(AR)로 착용해 볼 수 있는 ORDALABS만이 제공하는 디지털 자산입니다.',
    main_idx_6:'더 알아보기',
    main_idx_7:'ORDALABS와 함께 아티스트 또는 디지털 창작자로 참여하십시오',
    main_idx_8:'당신의 창의력에 날개를 달아주는 곳! ORDALABS의 확장성을 탐색하고 지원하십시오.',
    main_idx_9:'아티스트 신청',
    main_idx_10:'프로젝트 크리에이터 신청',
    main_idx_11:'멋진 디자인을 함께 만들어 갑시다.',
    main_idx_12:'인기 태그',
    main_idx_13:'공지사항',
    main_idx_14:'세상에 없던 선글라스 구독서비스',
    main_idx_15:'ORDALABS 선글라스 구독 서비스',
    main_idx_16:'ORDALABS 구독 서비스 소개',
    main_idx_17:'멤버쉽 1년 이용권',
    main_idx_18:'더 이상 안경이나 선글라스를 사지 마십시오. ORDALABS에서 구독하세요.',

    main_idx_19:'1개월 3개 아이템',
    main_idx_20:'한 달에 3개의 아이템을 빌릴 수 있습니다.',
    main_idx_21:'3주 사용',
    main_idx_22:'대여 아이템은 3주 동안 사용할 수 있습니다.',
    main_idx_23:'1년 36개 아이템',
    main_idx_24:'1년간 36개 품목을 대여할 수 있습니다.',


    curated_1:'작품들',
    curated_2:'품절되기 전에 이곳에서 구매하거나 또는 마켓플레이스에서 다른 참여자로부터 구매할 수 있습니다.',
    curated_3:'작품 발행일자',
    curated_4:'',

    mp_drops:'최근 엄선된 작품들',
    mp_pick:'ORDALABS에서 직접 선별하여 독점적으로 제공',
    mp_idx:'결과',
    mp_1:'둘러보기',
    mp_2:'정렬',
    mp_3:'최신 순',
    mp_4:'오래된 순',
    mp_5:'높은 가격순',
    mp_6:'낮은 가격순',
    mp_7:'제안 가능',
    mp_8:'1차 판매 작품',

    auc_0:'경매',
    auc_1:'총 0/5 판매',
    auc_2:'총 0/10 판매',
    auc_3:'총 1/3 판매',
    auc_4:'1개 모두 품절',

    ad_info:'아티스트 정보',
    ad_name:'',
    ad_note:'',
    ad_meet:'',
    ad_drops:'컬렉션 목록',

    com_1:'이메일 인증을 진행해주세요.',
    com_2:'이메일을 입력해 주세요.',
    com_3:'비밀번호를 입력해 주세요.',
    com_4:'회원 가입에 성공하였습니다.',
    com_5:'회원 가입에 실패하였습니다.',
    com_6:'정상적인 계정이 아닙니다. contact@starwings.co.kr로 문의 바랍니다.',
    com_7:'이메일 또는 비밀번호가 일치하지 않습니다.',
    com_8:'축하합니다! 경매에 낙찰 되었습니다. \n24시간 이내에 구매를 진행해 주시기 바랍니다.\n24시간 이내에 구매하지 않을 시 경매 참가가 제한됩니다.',

    meta_1:'이더리움 네트워크를 sepolia 테스트 네트워크로 변경 후 이용해 주세요.',
    meta_2:'이더리움 네트워크를 메인 네트워크로 변경 후 이용해 주세요.',
    meta_3:'메타마스크 지갑 연결을 확인해 주세요.',
    meta_4:'NFT 등록에 성공하였습니다.',
    meta_5:'NFT 등록에 실패하였습니다.',
    meta_6:'NFT 삭제에 실패하였습니다.',
    meta_7:'NFT 판매 중단에 성공하였습니다.',
    meta_8:'NFT 판매 중단에 실패하였습니다.',
    meta_9:'PC에서만 NFT 구매가 가능합니다.',
    meta_10:'나의 NFT는 구매할 수 없습니다.',
    meta_11:'NFT 구매에 실패하였습니다.',
    meta_12:'NFT 구매에 성공하였습니다.',
    meta_13:'NFT 구매에 실패하였습니다.',
    meta_14:'판매 가격을 확인해 주세요.',
    meta_15:'로열티를 확인해 주세요.',
    meta_16:'NFT 발행에 실패하였습니다.',

    meta_approve:'DSP로 구매 시 최초 1회 토큰 승인이 진행됩니다.',
    meta_buy_reject:'동일한 아이템을 판매 중이라 해당 아이템은 구매할 수 없습니다.',
    meta_dsp_no:'DSP 토큰이 충분하지 않습니다.',
    meta_dsp_zero:'보유하고 있는 DSP 토큰이 없습니다.',
    meta_again:'다시 한번 시도해 주세요.',
    meta_mo_call:'메타마스크를 호출합니다. 정상 동작하지 않을 경우 PC 버전을 이용해 주시기 바랍니다.',
    meta_approve_fail:'Approve에 실패하였습니다.',

    meta_connect:'메타마스크를 연결을 확인해 주세요.',



    mpa_1:	'이미 지갑 주소가 등록 되어 있습니다.',
    mpa_2:	'이미 다른 이용자가 사용 중인 지갑 주소입니다.',
    mpa_3:	'메타마스크 연결을 확인해 주세요.',
    mpa_4:	'이름을 입력해 주세요.',
    mpa_5:	'정보 수정에 성공하였습니다.',
    mpa_6:	'정보 수정에 실패하였습니다.',
    mpa_7:	'프로필 사진 등록에 성공하였습니다. 계속 다른 정보를 입력해 주세요.',
    mpa_8:	'사진 용량을 확인해 주세요. (최대 10MB)',
    mpa_9:	'사진 등록에 실패하였습니다.',
    mpa_10:	'변경된 정보가 없습니다.',


    wd_notice:'※ 주 의 사 항 ※<br><br>1. 송금 받을 MVR 지갑 주소 오기로 인한 송금 오류에 관하여 당사에서는 책임지지 않습니다.<br><br>2. 전환 신청 후 14일 간 유예 후 영업일에 등록한 송금 주소로 MVR 토큰이 송금됩니다.<br><br>3. 14일 간 유예 후 송금일이 토,일,공휴일일 경우 다음 영업일에 송금됩니다.<br><br>4. 전환 신청한 건에 관해서 전환 신청 취소가 불가합니다. <br><br>5. 8,000MVR Cash 이상 출금이 가능합니다. <br><br>',
    auc_notice:'※ 주 의 사 항 ※<br><br>1. 경매 낙찰 시 이메일로 낙찰 안내가 발송됩니다.<br><br>2. 경매 낙찰 시 24시간 이내에 구매하지 않을 경우 이후 경매 참가가 제한됩니다.<br>',
    offer_notice:'※ 주 의 사 항 ※<br><br>1. 제안 결과는 이메일로 안내가 발송됩니다.<br><br>2. 제안 승낙 시 판매자가 아이템 등록 후 24시간 이내에 구매하지 않을 경우 이후 제안 기능이 제한됩니다.<br>',
    alt_address:'올바른 지갑 주소가 아닙니다.\n다시 한번 확인 후 입력해 주세요.',
    alt_address_chk:'지갑 주소를 입력해 주세요.',
    alt_amount_chk:'출금 신청 수량을 입력해 주세요.',
    alt_my_amount_chk:'출금 가능 수량을 초과하였습니다.',
    alt_zero_chk:'정상적인 수량을 입력해 주세요.',
    alt_wd_success:'MVR 출금 신청이 완료 되었습니다.',
    alt_wd_fail:'MVR 출금 신청에 실패하였습니다.',
    alt_wd_low:'8,000MVR Cash부터 출금 가능합니다.',
    alt_reg_already:'이미 등록된 메일입니다.',
    alt_fail:'등록에 실패하였습니다.',

    wd_agree:'위 주의사항을 모두 읽었으며, 전환 신청에 동의합니다.',
    wd_1:'출금 가능 수량',
    wd_2:'송금 받을 MVR 지갑 주소',
    wd_3:'출금 신청 수량',

    close:'닫기',
    mem_del:'회원탈퇴에 성공하였습니다.',
    mem_del_btn:'회원탈퇴',
    auc_flag_no:'경매 참가가 제한된 계정입니다.',
    support_search:'ORDALABS에 대하여 궁금한 것을 검색해 보세요.',
    support_title:'어떻게 도와드릴까요?',
    support_notice:'공지사항',
    support_guide:'가이드',
    support_faq:'자주하는 질문',
    support_help:'도움이 필요하세요?',
    support_help_title:'저희에게 연락하시면 최대한 빨리 연락드리겠습니다.',
    support_help_btn:'지원 센터',
    support_more:'더 보기',


    col_items:'아이템',
    col_act:'활동 내역',
    col_filter:'필터',
    col_owners:'소유자',
    col_cate:'카테고리',
    col_status:'상태',
    col_price:'가격',
    col_filter_btn:'필터 적용',
    col_filter_sel1:'선택하세요.',
    col_filter_sel2:'선택하세요.',
    col_filter_status2:'경매',
    col_filter_status1:'판매중',

    reg_agree:'<a href="#" target="_blank" style="color:blue;">이용 약관</a>과 <a href="#" target="_blank" style="color:blue;">개인정보취급방침을</a> 확인하였고, 동의합니다.',
    reg_agree_fail:'이용약관과 개인정보취급방침을 동의해 주세요.'























};

$.lang.en = {
    menu_1:'Collections',
    menu_2:'Marketplace',
    menu_3:'History',
    menu_4:'Sign in',
    menu_5:'My Page',
    menu_6:'Support',
    menu_7:'Create',
    join_1: 'Email is available.',
    join_2: 'This email has already been used.',
    code_send: 'Send the authentication code.',
    code_fail: 'Failed to send authentication code.',
    code_success: 'It has been successfully authenticated.',
    code_failed: 'Authentication failed.',
    chk_price: 'Check the price.',
    sign_1:'ORDALABS NFT',
    sign_2:'Email Address',
    sign_3:'Password',
    sign_4:'LOG IN',
    sign_5:'Register',
    sign_6:'Forget Password?',
    register_1:'Email Address',
    register_2:'SEND',
    register_3:'Password',
    register_4:'Confirm Password',
    register_5:'Register',
    register_6:'Login',
    register_7:'Email Validation Code',
    register_8:'CONFIRM',
    register_9:'New Password',
    register_10:'CODE SEND',
    register_11:'Please enter your email address. After email verification is complete, you can set a new password.',
    register_12:'Password Change',
    register_13:'This is an unsigned email.',
    register_14:'Password reset successful.',
    register_15:'Password reset failed.',
    search_0:'Search',
    search_1:'Search results for ...',
    search_2:'Items',
    search_3:'Users',
    search_4:'Collections',
    my_0:'Owned',
    my_1:'My Favorite',
    my_2:'Bid ltem',
    my_3:'Creator',
    my_4:'for sale(listing)',
    my_5:'List for sales',
    my_6:'Successful bid',
    my_7:'Reward Amount(1 Day)',
    my_8:'Remaining Date',
    my_9:'No Reward',
    my_10:'Days',
    my_11:'Reward Date',
    my_12:'Offers',
    my_13:'Offer ON',
    my_14:'Offer OFF',
    my_15:'Receive',
    my_16:'Offer',
    my_17:'Offer',
    my_18:'Owner',
    my_19:'Offer Price',
    my_20:'Refusal',
    my_21:'Approval',
    my_22:'Pending Approval',
    my_23:'Purchase Failed',
    my_24:'Created',
    my_25:'Waiting for sale',
    my_26:'Delist',
    my_27:'Reject',

    cre_1:'Create Items',
    cre_2:'This is the process of creating an item before issuing the actual NFT.<br>Created items are displayed on My Page, and NFTs can be issued after the administrator\'s approval.<br>There is no Ethereum gas cost in the NFT creation process.',
    cre_3:'# NFT Thumbnail',
    cre_4:'JPG, PNG, GIF less than 10MB',
    cre_5:'# NFT Content File',
    cre_6:'*jpg, png, gif, mp4, glb less than 100MB',
    cre_7:'# Royalty Fee',
    cre_8:'Tag',
    cre_9:'Category',
    cre_10:'Create NFT',
    cre_11:'NOTE: Creating an item can take up to a minute. Please be patient during upload.',
    cre_12:'Upload file to preview your brand new NFT',
    cre_13:'Sales Type',
    cre_14:'Starting',
    cre_15:'Ending',

    profile_1:'Following',
    profile_2:'Followers',
    profile_3:'Joined',
    profile_4:'Edit Profile',
    profile_5:'Logout',
    profile_6:'Withdraw',
    edit_0:'Profile Image',
    edit_1:'REGISTER',
    edit_2:'User Name',
    edit_3:'Bio',
    edit_4:'Web site',
    edit_5:'Twitter',
    edit_6:'Instagram',
    edit_7:'Youtube',
    edit_8:'CLOSE',
    edit_9:'SAVE',
    nft_list:'List your item to sell as an NFT',
    nft_price:'Price',
    nft_edit:'# of editions to issue',
    nft_fee:'# Creator Royalty Fee(%)',
    nft_0:'Title',
    nft_1:'Description',
    nft_2:'The dynamic appearance of pigs, one of human-friendly animals, will be released as NFT that combines Web 3D AR contents and blockchain technology through animation. Collectors can take pictures and videos of animations through the ORDALABS NFT Marketplace mobile service.',
    nft_3:'Fees',
    nft_4:'Service Fee',
    nft_5:'% of sales price will be deducted for Service fee when the item is sold.',
    nft_6:'The process is to mint the above item as NFT and lists it on the ORDALABS Marketplace. Meta data of the item will be stored in the blockchain, and it may incur Ethereum gas fee.',
    nft_7:'Listing NFT(Resell)',
    nft_9:'Listing NFT(Offer)',
    nft_8:'NOTE: Creating an item can take up to a minute. Please be patient during upload.',
    ac_title:'Sitewide Activity',
    ac_desc:'This page shows all offers, sales, and purchases happening on ORDALABS live.',
    ac_sale:'Sale',
    ac_offer:'Offer',
    ac_mins:'10minutes ago',
    ac_list:'Listing',
    ac_withdraw:'Transfer',
    art_admin:'Creator',
    art_type:'Sales Type',
    art_remain:'Remain Amount',
    art_1:'AUCTION',
    art_2:'Auction ending in',
    art_3:'Day',
    art_4:'Hrs',
    art_5:'Mins',
    art_6:'Current Price',
    art_7:'Place a bid',
    art_8:'Rank',
    art_9:'Name',
    art_10:'Bid price',
    art_11:'Time',
    art_12:'No bids made yet ',
    art_13:'Resell',
    art_14:'Bids',
    art_15:'Price',
    art_16:'Buy Now(Auction)',
    art_17:'Buy Now',
    art_18:'Secs',
    art_19:'Current Bid Price',
    ac_own:'owners',
    ac_total:'total',
    ac_views:'views',
    ac_fave:'favorites',
    md_0:'Type',
    md_1:'Created by',
    md_2:'Original Price',
    md_3:'View on IPFS',
    md_4:'View IPFS Metadata',
    md_5:'Maketplace items',
    md_6:'No',
    md_7:'Owned by',
    md_8:'Last Sale Price',
    md_9:'Last Sale Time',
    md_10:'List Price',
    md_11:'No Transaction',
    md_12:'View on Etherscan',
    md_13:'History',
    md_14:'Transaction',
    md_15:'My Item',
    md_16:'Buy Now',
    md_17:'Sold Out',
    md_18:'Not for sale',
    md_19:'Item',
    md_20:'Make Offer',
    md_21:'Offer Buy',
    md_more:'MORE ITEM',
    md_more_item:'More items by',
    md_collection:'Collection',

    pro_0:'Admin',
    pro_1:'Follow',
    pro_2:'Following',
    pro_3:'Followers',
    pro_4:'Joined',
    pro_5:'Owned',
    pro_6:'No Items',

    ad_buy:'The final bid was awarded.Please purchase by clicking the Buy button within 24 hours. If you do not purchase within 24 hours, you will be banned from participating in the auction.',
    ad_low:'A bid that is lower than the highest bid.',
    chk_sign:'Please Sign in.',
    bid_1:'Please enter your bid.',
    bid_2:'The bid was successful.',
    bid_3:'Lower than current bid.',
    bid_4:'Failed to bid.',
    bid_5:'Please bid within the cryptocurrency you have.',

    offer_1:'Please offer within the cryptocurrency you have.',
    offer_2:'The offer was successful.',
    offer_3:'Failed to offer.',
    offer_4:'Please enter your offer.',
    offer_5:'The offer registration was successful.',
    offer_6:'The same item has already been registered for sale.',
    offer_7:'I have successfully declined the offer.',
    offer_8:'I have already offered the price. If you refuse, I can make another suggestion.',




    chk_email:'Please check email.',
    chk_drops:'Would you like to subscribe to drops?',
    chk_sub:'Your subscription is complete.',
    chk_price:'Check the price.',


    main_live:'Live NFT Auctions',
    main_recent:'Recent goods',

    main_idx_1:'Subscribe to our ultra-exclusive drop list and be the first to know about upcoming ORDALABS drops.',
    main_idx_2:'Popular works provided only by ORDALABS',
    main_idx_3:'browse marketplace',
    main_idx_4:'The Extended Reality Marketplace for ORDALABS',
    main_idx_5:'ORDALABS is a premium marketplace where you can truly own digital items. And it is a digital asset provided only by ORDALABS that can be seen with you in photos and videos anytime, anywhere.',
    main_idx_6:'learn more',
    main_idx_7:'Join as an artist or digital creatior with ORDALABS',
    main_idx_8:'A place that gives wings to your creativity! Explore and support our extensibility to ORDALABS.',
    main_idx_9:'l am an artist',
    main_idx_10:'i am a project creator',
    main_idx_11:'Let\'s make a great<br>design togerther',
    main_idx_12:'Popular Tag',
    main_idx_13:'NOTICE',
    main_idx_14:'it\'s all about the glasses',
    main_idx_15:'ORDALABS Glasses Subscribe Service',
    main_idx_16:'About ORDALABS Subscribe',
    main_idx_17:'1 year membership pass',
    main_idx_18:'Don\'t buy glasses or sunglasses anymore. Subscribe at ORDALABS.',

    main_idx_19:'3 per month',
    main_idx_20:'3 items can be rented per month.',
    main_idx_21:'3 weeks',
    main_idx_22:'Rental items can be used for 3 weeks.',
    main_idx_23:'36 per year',
    main_idx_24:'36 items can be rented per year.',

    curated_1:'Drops',
    curated_2:'You can buy them here before they sell out - or purchase them from other users on the secondary marketplace.',
    curated_3:'Artwork to be released on 2021-12-23',
    curated_4:'Artwork to be released on 2021-12-17',

    mp_drops:'Recent Curated Drops',
    mp_pick:'Hand selected and exclusively dropped on ORDALABS',
    mp_idx:'results',
    mp_1:'Browse',
    mp_2:'sort by',
    mp_3:'latest',
    mp_4:'oldest',
    mp_5:'highest price',
    mp_6:'lowest price',
    mp_7:'offer',
    mp_8:'create item',

    auc_0:'Auction',
    auc_1:'Total 0 of 5 sales',
    auc_2:'Total 0 of 10 sales',
    auc_3:'Total 1 of 3 sales',
    auc_4:'All 1 are sold out',

    ad_info:'Artist Info',
    ad_name:'ORDALABS NFT First Collection by XR Artist An Ji-Hyun',
    ad_note:'Artist Note',
    ad_meet:'Meet Artist',
    ad_drops:'Explore Collection',

    com_1:'Please verify your email.',
    com_2:'Please enter your email.',
    com_3:'Please enter a password.',
    com_4:'Membership registration was successful.',
    com_5:'Failed to sign up.',
    com_6:'The account is suspended. For more information, please contact us via email contact@starwings.co.kr.',
    com_7:'Wrong email or password.',
    com_8:'Congratulations.\nThe final bid was awarded.\nIf you do not purchase within 24 hours, you will be banned from participating in the auction.',


    meta_1:'Please use after changing the Ethereum network to the sepolia test network.',
    meta_2:'Please use after changing the Ethereum network to the Mainnet network.',
    meta_3:'Its not a connected wallet address.',
    meta_4:'NFT registration successful.',
    meta_5:'NFT registration failed.',
    meta_6:'Failed to Burn NFT.',
    meta_7:'Delist succeeded.',
    meta_8:'Delist failed.',
    meta_9:'This function is only available on PC.',
    meta_10:'My items cannot be purchased.',
    meta_11:'Failed to buy NFT.',
    meta_12:'NFT purchase success.',
    meta_13:'NFT purchase failed.',
    meta_14:'Check the price.',
    meta_15:'Check the royalty.',
    meta_16:'Failed to Mint NFT.',

    meta_approve:'Token approval is only required once for purchase through DSP.',
    meta_buy_reject:'The same item is registered for sale and cannot be purchased.',
    meta_dsp_no:'There are not enough DSP tokens.',
    meta_dsp_zero:'You do not have any DSP tokens in your possession.',
    meta_again:'Please try again.',
    meta_mo_call:'Call metamask. If it does not work properly, please use the PC version.',
    meta_approve_fail:'Failed to Approve.',

    meta_connect:'Please check the metamask connection.',

    mpa_1:	'This is an account with a wallet already registered.',
    mpa_2:	'This is an already registered wallet address.',
    mpa_3:	'Please check the metamask connection.',
    mpa_4:	'Please enter your name.',
    mpa_5:	'Information change was successful.',
    mpa_6:	'Information change failed.',
    mpa_7:	'You have changed your profile image.\n Please enter other information.',
    mpa_8:	'You have exceeded the maximum upload capacity.',
    mpa_9:	'Registration failed.',
    mpa_10:	'No information has changed.',

    alt_address:'This is not a valid wallet address.\n Please check it again and enter it.',
    alt_address_chk:'Please enter your wallet address.',
    alt_amount_chk:'Please enter the withdrawal request amount.',
    alt_my_amount_chk:'The amount that can be withdrawn has been exceeded.',
    alt_zero_chk:'Please enter the normal quantity.',
    alt_wd_success:'The withdrawal request was successful.',
    alt_wd_fail:'Failed to apply for withdrawal.',
    alt_wd_low:'You can withdraw from 8,000 MVR Cash.',
    alt_reg_already:'This email is already registered.',
    alt_fail:'Failed.',

    wd_notice:'※ Precautions ※<br><br>1. We are not responsible for any remittance errors caused by an incorrect MVR wallet address to receive remittance.<br><br>2. After a 14-day grace period after conversion application, MVR tokens will be sent to the registered remittance address on business days.<br><br>3. If the remittance date falls on a Saturday, Sunday or holiday after 14 days of grace, remittance will be made on the next business day.<br><br>4. It is not possible to cancel a conversion request for a conversion request.<br><br>5. Withdrawal of more than 8,000 MVR Cash is possible.<br><br>',
    auc_notice:'※ Precautions ※<br><br>1. When the auction is successful, you will be notified of the successful bid by e-mail.<br><br>2. If you do not purchase within 24 hours of winning the auction, you will be restricted from participating in the subsequent auction.<br>',
    offer_notice:'※ Precautions ※<br><br>1. Proposal results will be notified by e-mail.<br><br>2. When the offer is accepted, if the seller does not purchase within 24 hours of registering the item, the subsequent offer function will be limited.<br>',
    wd_agree:'I have read all of the above notices and agree to the conversion application.',
    wd_1:'Available Quantity',
    wd_2:'MVR wallet address',
    wd_3:'Application Quantity',

    close:'CLOSE',
    mem_del:'You have successfully canceled your membership.',
    mem_del_btn:'Membership Withdrawal',
    auc_flag_no:'This account is restricted from participating in auctions.',

    support_search:'Search for any questions you may have about ORDALABS.',
    support_title:'How can we help?',
    support_notice:'NOTICE',
    support_guide:'GUIDE',
    support_faq:'FAQ',
    support_help:'Need Any Helps?',
    support_help_title:'Contact us and we’ll get back to you as soon as we can.',
    support_help_btn:'Help Center',
    support_more:'more',

    col_items:'Items',
    col_act:'Activity',
    col_filter:'Filter',
    col_owners:'Owners',
    col_cate:'Categories',
    col_status:'Status',
    col_price:'Price',
    col_filter_btn:'Apply Filter',
    col_filter_sel1:'Select Category',
    col_filter_sel2:'Select Currency',
    col_filter_status2:'On Auction',
    col_filter_status1:'Buy Now',

    reg_agree:'I have read and agree to the <a href="#" target="_blank" style="color:blue;">Terms of Use</a> and <a href="#" target="_blank" style="color:blue;">Privacy Policy.</a>',
    reg_agree_fail:'Please agree to the Terms of Use and Privacy Policy.'


};

//中文
$.lang.cn = {
    menu_1:'收藏',
    menu_2:'市场',
    menu_3:'历史',
    menu_4:'登录',
    menu_5:'我的页面',
    menu_6: '通知',
    menu_7:'创建NFT',
    join_1: '此邮箱可注册。',
    join_2: '此邮箱已注册。',
    code_send: '验证码已发送。',
    code_fail: '发送验证码失败。',
    code_success: '邮箱验证成功。',
    code_failed: '邮件验证失败。',
    chk_price: '请检查销售成本。',
    sign_1:'奥达实验室',
    sign_2:'电子邮件地址',
    sign_3:'密码',
    sign_4:'登录',
    sign_5: '注册会员',
    sign_6:'忘记密码了？',
    register_1:'电子邮件',
    register_2:'认证',
    register_3:'密码',
    register_4:'重新确认密码',
    register_5:'注册',
    register_6:'登录',
    register_7:'验证验证码',
    register_8: '确认',
    register_9:'新密码',
    register_10:'认证',
    register_11:'邮箱验证完成后可以重设密码。请验证您的电子邮件。',
    register_12:'更改密码',
     register_13:'该邮箱并未注册会员。',
     register_14:'密码重置成功。',
     register_15:'密码重置失败。',
     search_0:'搜索',
     search_1:'搜索结果',
     search_2:'项目',
     search_3:'用户',
     search_4:'收藏',
     my_0:'拥有的作品',
     my_1:'收藏夹',
     my_2:'投标作品',
     my_3:'出版者',
     my_4:'销售中',
     my_5:'销售',
     my_6:'中标产品',
     my_7:'每日奖励数量',
     my_8:'剩余奖励期',
     my_9:'没有奖励',
     my_10:'日',
     my_11:'奖励支付期限',
     my_12:'提案的作品',

     my_13:'提案开启',
     my_14:'提案关闭',
     my_15:'收集提案',
     my_16:'提案箱',
     my_17:'提案者',
     my_18:'所有者',
     my_19:'提案价格',
     my_20:'拒绝',
     my_21:'批准',
     my_22:'等待批准',
     my_23:'购买失败',
     my_24:'已发行作品',
     my_25:'销售批准中',
     my_26:'取消销售',
     my_27:'拒绝销售',

     cre_1:'创建项目',
     cre_2:'这是在发行实际NFT之前创建项目的过程。<br>创建的项目显示在我的页面上，管理员批准后可以发行NFT。<br>在NFT创建过程中，以太坊gas不产生任何费用。',
     cre_3:'# NFT缩略图',
     cre_4:'JPG、PNG、GIF 10MB 以下',
     cre_5:'#NFT内容文件',
     cre_6:'*jpg、png、gif、mp4、glb小于100MB',
     cre_7:'#销售版税',
     cre_8:'标签',
     cre_9:'类别',
     cre_10:'创建 NFT',
     cre_11:'注意：创建项目可能需要几分钟时间。上传中请稍候',
     cre_12:'如想预览新的NFT，请上传文件',
     cre_13: '销售类型',
     cre_14:'开始日期',
     cre_15:'结束日期',

    profile_1:'关注',
    profile_2:'粉丝',
    profile_3:'加入',
    profile_4:'编辑个人资料',
    profile_5:'注销',
    profile_6:'申请提款',
    edit_0:'个人资料图片',
    edit_1:'注册',
    edit_2:'名称',
    edit_3:'简介',
    edit_4:'网站',
    edit_5:'推特',
    edit_6:'Instagram',
    edit_7:'YouTube',
    edit_8:'关闭',
    edit_9:'保存',
    nft_list:'用NFT查看出售项目',
    nft_price:'售价',
    nft_edit:'要发布的版本数',
    nft_fee:'初始发行人特许权使用费',
    nft_0:'标题',
    nft_1:'详细信息',
    nft_2:'',
    nft_3:'手续费',
    nft_4:'服务费',
    nft_5:'项目售出时，从售价中扣除相应的服务费。',
    nft_6:'这个过程是将上述项目作为NFT发行并奥达实验室在市场上注册。该项目的元数据存储在区块链上，可能需要支付以太坊汽油费。',
    nft_7:'NFT 注册（转售）',
    nft_9:'NFT 注册（提案）',
    nft_8:'注意：注册项目可能需要几分钟时间。请稍等。 ',
    ac_title:'网站交易状态',
    ac_desc:'此页面显示奥达实验室网站上所有项目的注册、销售和购买状态。',
    ac_sale:'销售',
    ac_offer:'提案',
    ac_mins:'10分钟前',
    ac_list:'注册',
    ac_withdraw:'转移',
    art_admin:'出版者',
    art_type:'销售类型',
    art_remain:'剩余数量',
    art_1:'拍卖',
    art_2:'拍卖结束',
    art_3:'日',
    art_4:'时',
    art_5:'分钟',
    art_6:'当前价格',
    art_7:'投标',
    art_8:'排名',
    art_9:'名字',
    art_10:'投标价格',
    art_11:'时间',
    art_12:'没有投标',
    art_13:'再次投标',
    art_14:'投标状态',
    art_15:'固定价销售',
    art_16:'购买（拍卖）',
    art_17:'购买',
    art_18:'秒',
    art_19:'当前投标价格',
    ac_own:'所有者',
    ac_total:'发行总数',
    ac_views:'浏览量',
    ac_fave:'收藏夹',
    md_0:'类型',
    md_1:'出版者',
    md_2:'原价',
    md_3:'在IPFS中查看',
    md_4:'查看IPFS元数据',
     md_5:'市场项目',
     md_6:'号码',
     md_7:'所有者',
     md_8:'最后售价',
     md_9:'最后销售时间',
     md_10:'标价',
     md_11:'没有交易',
     md_12:'查看Etherscan',
     md_13:'交易详情',
     md_14:'交易历史',
     md_15:'我的项目',
     md_16:'购买',
     md_17:'售罄',
     md_18:'未售出',
     md_19:'项目',
     md_20:'提案',
     md_21:'买入（提案）',
     md_more:'更多',
     md_more_item:'更多项目',
     md_collection:'收藏',

     pro_0:'取消关注',
     pro_1:'关注',
     pro_2:'关注',
     pro_3:'粉丝',
     pro_4:'加入',
     pro_5:'拥有的作品',
     pro_6:'没有作品。',
     ad_buy:'您的投标已经中标。请在24小时内点击购买按钮购买。如您未在24小时内购买，您将被限制参与拍卖。',
     ad_low:'您的投标价低于最高投标价。',
     chk_sign:'请登录后使用。',
     bid_1:'请输入您的投标价。',
     bid_2:'您的投标已成功。',
     bid_3:'低于当前投标价。',
     bid_4:'投标失败。',
     bid_5:'请在您拥有的虚拟资产范围内投标。',
     offer_1:'请在您拥有的虚拟资产范围内提案。',
     offer_2:'提案成功。',
     offer_3:'提案失败。',
     offer_4:'请输入提案价格。',
     offer_5:'您已成功注册接收提案价。',
     offer_6:'因相同的作品已在售，您无法收到提案价。',
     offer_7:'已成功拒绝提案。',
     offer_8:'已存在提案。如被拒绝，可再次提案。',

     chk_email:'请检查您的电子邮件。',
     chk_drops:'确定接收新作品吗？',
     chk_sub:'订阅已完成。',
     chk_price:'请查看售价。',

     main_live:'实时NFT拍卖',
     main_recent:'最新商品',

   // 主页服务主句 // 需要主页设置内容
    main_idx_1:'订阅奥达实验室项目的独家发布列表，第一时间了解新注册项目。',
    main_idx_2:'热门作品',
    main_idx_3:'市场浏览',
    main_idx_4:'基于增强现实(AR)的市场奥达实验室',
    main_idx_5:'奥达实验室是一个高级市场，您可以在其中真正拥有数字项目。而这个数字项目是只有奥达实验室提供的数字资产，可以随时随地在增强现实（AR）一起佩戴。',
    main_idx_6:'了解更多',
    main_idx_7:'和奥达实验室一起作为艺术家或数字创作者加入',
    main_idx_8:'一个为您的创造力插上翅膀的地方！探索和支持奥达实验室的可扩展性.',
    main_idx_9:'艺术家申请',
    main_idx_10:'项目创建者应申请',
    main_idx_11:'让我们一起创作杰出的设计。',
    main_idx_12:'热门标签',
    main_idx_13:'通知',

     main_idx_14:'世界上没有的墨镜订阅服务',
     main_idx_15:'奥达实验室墨镜订阅服务',
     main_idx_16:'奥达实验室订阅服务介绍',
     main_idx_17:'会员1年使用券',
     main_idx_18:'不要再买眼镜或太阳镜了。请订阅 奥达实验室.',


     main_idx_19:'每月3款物品',
     main_idx_20:'每个月可以借3件物品。',
     main_idx_21:'使用3周',
     main_idx_22:'租赁物品可以使用3周。',
     main_idx_23:'每年36件物品',
     main_idx_24:'您每年可以租36件物品。',
     // 主页服务主要短语 //

     curated_1:'作品',
     curated_2:'您可以在售罄之前在这里购买，或者从市场上的其他参与者那里购买。',
     curated_3:'作品的出版日期',
     curated_4:'',

     mp_drops:'近期入选作品',
     mp_pick:'直接从奥达实验室中选择并独家提供',
     mp_idx:'结果',
     mp_1:'逛逛',
     mp_2:'排序',
     mp_3:'最新',
     mp_4:'最久',
     mp_5:'最高价',
     mp_6:'最低价',
     mp_7:'可报价',
     mp_8:'第一次销售作品',

     auc_0:'拍卖',
     auc_1:'销售了0/5',
     auc_2:'销售了0/10 ',
     auc_3:'销售了1/3',
     auc_4:'1件已售罄',

     ad_info:'艺术家信息',
     ad_name:'',
     ad_note:'',
     ad_meet:'',
     ad_drops:'收藏列表',

     com_1:'请验证您的电子邮件。',
     com_2:'请输入您的邮箱。',
     com_3:'请输入您的密码。',
     com_4:'会员注册已成功。',
     com_5:'会员注册失败。',
     com_6:'该帐户信息异常。 请通过*电子邮件地址*与我们联系',
     com_7:'邮箱或密码不匹配',
     com_8:'恭喜！您已赢得了本次拍卖。\n请在24小时内购买。\n如果您未在24小时内购买，您将被限制参与拍卖。',

     meta_1:'请将以太坊网络更改为sepolia测试网络后使用。',
     meta_2:'请将以太坊网络改为主网后使用。',
     meta_3:'请检查元掩码钱包连接。',
     meta_4:'NFT注册成功。',
     meta_5:'NFT注册失败。',
     meta_6:'NFT删除失败。',
     meta_7:'成功停止出售NFT。',
     meta_8:'停止出售NFT失败。',
     meta_9:'NFT购买功能仅在PC上可用。',
     meta_10:'我的NFT无法购买。',
     meta_11:'NFT购买失败。',
     meta_12:'NFT购买成功。',
     meta_13:'NFT购买失败。',
     meta_14:'请查看售价。',
     meta_15:'请检查版税。',
     meta_16:'NFT发布失败。',

     // 自有代币交易的语句
     meta_approve:'如果您使用*代币名称*购买，将完成第一个代币批准。',
     meta_buy_reject:'无法购买该物品，因为正在出售相同的物品。',
     meta_dsp_no:'*代币名称* 没有足够的代币。',
     meta_dsp_zero:'库存中没有 *代币名称* 代币。',
     meta_again:'请再试一次。',
     meta_mo_call:'调用元掩码。 如果不能正常使用，请使用PC版。',
     meta_approve_fail:'批准失败。',
     // 自有代币交易的短语
     meta_connect:'请检查元掩码连接。',



     mpa_1: '你的钱包地址已经注册。',
     mpa_2: '该钱包地址已被其他用户使用。',
     mpa_3: '请检查元掩码连接。',
     mpa_4: '请输入名字',
     mpa_5: '修改信息成功。',
     mpa_6: '修改信息失败。',
     mpa_7: '上传个人头像成功。请继续输入其他信息。',
     mpa_8: '请检查照片尺寸。（最大10MB）',
     mpa_9: '上传照片失败。',
     mpa_10: '没有信息被改变。',

   // 提取奖励代币时的语句 //
    wd_notice:'※注意事项※<br><br>1.我们不对由于要汇款的 *代币名称* 钱包地址不正确而导致的任何汇款错误负责。<br><br>2.在转换申请后的14天宽限期后，*代币名称* 代币将在工作日发送到注册的汇款地址。<br><br>3.如果汇款日期在14天宽限期后是周六、周日或节假日，则汇款将在下一个工作日发送。<br><br>4.无法取消转换请求后的转换请求。 <br><br>5。超过8,000*代币名称* Cash可提取。 <br><br>',
    auc_notice:'※注意事项※<br><br>1.拍卖成功后，将通过电子邮件通知您中标。<br><br>2.如果您在中标后24小时内未购买，您将被限制参与拍卖。<br>',
    offer_notice:'※ 注意事项※<br><br>1.提案结果将通过电子邮件通知。<br><br>2.报价被接受时，如果卖家在注册物品后24小时内未购买该物品时，后续提案功能将受到限制。<br>',
     alt_address:'这不是一个有效的钱包地址。\n请检查并重新输入。',
     alt_address_chk:'请输入钱包地址。',
     alt_amount_chk:'请输入要求提款的数量。',
     alt_my_amount_chk:'已经超过可提现的数量。',
     alt_zero_chk:'请输入正常数量。',
     alt_wd_success:'*代币名称*提现请求已完成。',
     alt_wd_fail:'*代币名称*提款请求失败。',
     alt_wd_low:'可从8,000*代币名称* Cash开始提现。',
     alt_reg_already:'此邮件已注册。',
     alt_fail:'注册失败。',

     wd_agree:'我已阅读以上所有通知并同意转换申请。',
     wd_1:'可提款金额',
     wd_2:'收款*代币名称*钱包地址',
     wd_3:'提款申请的数量',
     // 提取奖励代币时的语句 //

     close:'关闭',
     mem_del:'您已成功取消会员资格。',
     mem_del_btn:'退出会员',
     auc_flag_no:'您的账户被限制参与拍卖。',
     support_search:'搜索有关奥达实验室的问题。',
     support_title:'如何帮您？',
     support_notice:'通知',
     support_guide:'指南',
     support_faq:'常见问题',
     support_help:'需要帮助吗？',
     support_help_title:'联系我们，我们会尽快回复您。',
     support_help_btn:'客服中心',
    support_more:'更多',


     col_items:'项目',
     col_act:'活动历史',
     col_filter:'过滤器',
     col_owners:'所有者',
     col_cate:'类别',
     col_status:'状态',
     col_price:'价格',
     col_filter_btn:'应用过滤器',
     col_filter_sel1:'请选择',
     col_filter_sel2:'请选择',
     col_filter_status2:'拍卖',
     col_filter_status1:'销售中',

     reg_agree:'<a href="#" target="_blank" style="color:blue;">이용 약관</a>과 <a href="#" target="_blank" style="color:blue;">개인정보취급방침을</a> 확인하였고, 동의합니다.',
     reg_agree_fail:'同意使用条款和隐私政策。'

};

//일본어
$.lang.jp = {
menu_1:'コレクション',
menu_2:'マーケットプレイス',
menu_3:'ヒストリー',
menu_4:'ログイン',
menu_5:'マイページ',
menu_6:'お知らせ',
menu_7:'NFT生成',
join_1: '登録可能なEメールです',
join_2: '登録済みのEイーメールです',
code_send: '認証コードを発信しました',
code_fail: '認証コードの発信に失敗しました',
code_success: 'Eメールの認証に成功しました',
code_failed: 'Eメールの認証に失敗しました ',
chk_price: '販売費用を確認してください',
sign_1:'オルダラブ',
sign_2:'Eメールアドレス',
sign_3:'パスワード',
sign_4:'ログイン',
sign_5:'会員登録',
sign_6:'パスワードを忘れた場合',
register_1:'Eメール',
register_2:'認証する',
register_3:'パスワード',
register_4:'パスワード再確認',
register_5:'登録する',
register_6:'ログイン',
register_7:'認証番号確認',
register_8:'確認',
register_9:'新しいパスワード',
register_10:'認証する',
register_11:'Eメールの認証が完了したら、パスワードをリセットできます。Eメールの認証を進めてください',
register_12:'パスワード変更',
register_13:'登録されていないEメールです',
register_14:'パスワードのリセットに成功しました',
register_15:'パスワードのリセットに失敗しました',
search_0:'検索',
search_1:'検索結果',
search_2:'アイテム',
search_3:'使用者',
search_4:'コレクション',
my_0:'所有した作品',
my_1:'ブックマーク',
my_2:'入札作品',
my_3:'発行者',
my_4:'販売中',
my_5:'販売する',
my_6:'落札品',
my_7:'一日報償数量',
my_8:'残りの報償期間',
my_9:'報償なし',
my_10:'日',
my_11:'報償支給期間',
my_12:'提案作品',

my_13:'提案 ON',
my_14:'提案 OFF',
my_15:'提案を受ける',
my_16:'提案する',
my_17:'提案者',
my_18:'所有者',
my_19:'提案価格',
my_20:'断る',
my_21:'承認',
my_22:'承認待ち',
my_23:'購入失敗',
my_24:'発行作品',
my_25:'販売承認中',
my_26:'販売取り消し',
my_27:'販売差し戻し',

cre_1:'アイテム生成',
cre_2:'実際にNFTを発行する前にアイテムを生成する過程です.<br>生成されたアイテムはマイページに表示され、管理者の承認の後、NFTを発行することができます。<br>NFT生成過程では、イーサリアムガス代は発生しません',
cre_3:'# NFT サムネイル',
cre_4:'JPG, PNG, GIF 10MB 以下',
cre_5:'# NFT コンテンツファイル',
cre_6:'*jpg, png, gif, mp4, glb 100MB 以下',
cre_7:'# 販売ロイヤルティー',
cre_8:'タッグ',
cre_9:'カテゴリー',
cre_10:'NFTを生成する',
cre_11:'参考: 項目を作成するのに数分がかかる場合があります。アップロードの間、少々お待ちください。',
cre_12:'新しいNFTファイルをプレビューするためには、ファイルをアップロードしてください。',
cre_13:'販売タイプ',
cre_14:'開始日',
cre_15:'終了日',

profile_1:'ファロー',
profile_2:'フォロワー',
profile_3:'登録',
profile_4:'プロフィール編集',
profile_5:'ログアウト',
profile_6:'出金申請',
edit_0:'プロフィールイメージ',
edit_1:'アップロードする',
edit_2:'名前',
edit_3:'紹介',
edit_4:'ウエブサイト',
edit_5:'ツイッター',
edit_6:'インスタグラム',
edit_7:'ユーチューブ',
edit_8:'閉じる',
edit_9:'保存',
nft_list:'NFTで販売するアイテムを見る',
nft_price:'販売価格',
nft_edit:'発行するエディションの数',
nft_fee:'初回発行者のロイヤルティー手数料 ',
nft_0:'タイトル',
nft_1:'詳細',
nft_2:'',
nft_3:'手数料',
nft_4:'サービス手数料',
nft_5:'アイテムが販売されるとき、販売価格のサービス手数料分だけ差し引かれます',
nft_6:'この過程は、上記のアイテムをNFTで発行し、オルダラブ マーケットプレイスに登録することです。 アイテムのメタデータはブロックチェーンに保存され、イーサリアムガス代が課される場合があります。 ',
nft_7:'NFT登録(再販売)',
nft_9:'NFT登録(提案)',
nft_8:'参考：アイテムを登録するのに数分がかかる場合があります。少々お待ちください。',
ac_title:'サイトの取引現況',
ac_desc:'このページはオルダラブ サイトで発生するすべてのアイテムの登録、販売及び購入現況を示します。',
ac_sale:'販売',
ac_offer:'提案',
ac_mins:'１０分前',
ac_list:'登録',
ac_withdraw:'移行',
art_admin:'発行者',
art_type:'販売タイプ',
art_remain:'残りの数量',
art_1:'競売',
art_2:'競売終了',
art_3:'日',
art_4:'時',
art_5:'分',
art_6:'現在の価格',
art_7:'入札する',
art_8:'順位',
art_9:'名前',
art_10:'入札価格',
art_11:'時間',
art_12:'入札なし',
art_13:'リーセル',
art_14:'入札現況',
art_15:'固定価販売',
art_16:'購入する(競売)',
art_17:'購入する',
art_18:'秒',
art_19:'現在の入札価格',
ac_own:'所有者',
ac_total:'総発行',
ac_views:'クリック数',
ac_fave:'ブックマーク',
md_0:'タイプ',
md_1:'発行者',
md_2:'元の価格',
md_3:'IPFSで見る',
md_4:'IPFS メタデータを見る',
md_5:'マーケットプレイスアイテム',
md_6:'番号',
md_7:'所有者',
md_8:'最後の販売価格',
md_9:'最後の販売時間',
md_10:'定価',
md_11:'取引なし',
md_12:'イーサスキャンを見る',
md_13:'取引内訳の現況',
md_14:'取引内訳',
md_15:'私のアイテム',
md_16:'購入する',
md_17:'品切り',
md_18:'未販売',
md_19:'アイテム',
md_20:'提案する',
md_21:'購入(提案)',
md_more:'もっと見る',
md_more_item:'もっと多いアイテム',
md_collection:'コレクション',

pro_0:'アンフォロー',
pro_1:'フォロー',
pro_2:'フォローイング',
pro_3:'フォロアー',
pro_4:'登録',
pro_5:'所有作品',
pro_6:'作品がありません。',
ad_buy:'最終落札されました。２４時間以内に購入ボタンを押して購入してください。２４時間以内に購入しない場合、競売への参加が制限されます。',
ad_low:'最高入札価格より低い入札価格です。',
chk_sign:'ログインの後ご利用ください',
bid_1:'入札価格入力してください。',
bid_2:'入札に成功しました。',
bid_3:'現在の入札価格より低いです。',
bid_4:' 入札に失敗しました。',
bid_5:'保有している仮想通貨内で入札してください。',
offer_1:' 保有している仮想通貨内で提案してください。.',
offer_2:' 提案に成功しました。',
offer_3:' 提案に失敗しました',
offer_4:' 提案価格を入力してください。',
offer_5:'提案価格の受け取り登録に成功しました。',
offer_6:'既に同じ作品が販売中のため、提案価格を受けることができません。',
offer_7:'提案拒絶に成功しました。',
offer_8:'既に提案した価格があります。拒絶の場合、再度提案することができます。',

chk_email:'Eメールを確認してください。',
chk_drops:'新規作品をお受け取りになりますか。',
chk_sub:'購読の申し込みが完了しました。',
chk_price:'販売価格を確認してください。',

main_live:'ライブタイムNFT競売',
main_recent:'最近登録された商品',

// 메인페이지 서비스 주요 문구 // 메인페이지 세팅 내용 필요
main_idx_1:'オルダラブ アイテムの独点的な発行リストを購読し、新しい登録アイテムについて最初に知ることができます。',
main_idx_2:'人気作品',
main_idx_3:'マーケットプレイスを見回す',
main_idx_4:' 拡張現実 (AR)べーすのマーケットプレイス オルダラブ',
main_idx_5:'オルダラブは、デジタルアイテムを真に所有できるプレミアムマーケットプレイスです。そしてこのデジタルアイテムは、いつどこでも拡張現実として着用できるオルダラブだけが 提供するデジタル資産です。',
main_idx_6:'もっと調べる',
main_idx_7:'オルダラブと共にアーティスト又はデジタルクリエイターとして参加してください。',
main_idx_8:'貴方の想像力に翼をつけてくれるところ！オルダラブ拡張性を探索し、エントリーしてください。',
main_idx_9:'アーティスト申請',
main_idx_10:'プロジェクトクリエイター申請',
main_idx_11:' 素晴らしいデザインを一緒に作っていきましょう。',
main_idx_12:'人気タッグ',
main_idx_13:'お知らせ',

main_idx_14:'世界になかったサングラス購読サービス',
main_idx_15:'オルダラブサングラス購読サービス',
main_idx_16:'オルダラブ購読サービス紹介',
main_idx_17:'メンバーシップ１年利用権',
main_idx_18:'もう眼鏡やサングラスは買わなくても大丈夫です。オルダラブで購読してください。',


main_idx_19:'１ヵ月３つのアイテム ',
main_idx_20:'1ヶ月に３つのアイテムを借りることができます。',
main_idx_21:'３週間使用',
main_idx_22:'レンタルアイテムは３週間利用いただけます。',
main_idx_23:'１年３６個のアイテム',
main_idx_24:'１年間３６個のアイテムを借りることができます。',
// 메인페이지 서비스 주요 문구 //

curated_1:'作品',
curated_2:'品切りになる前にここで購入するか、マーケットプレイスで他の参加者から購入することができます。',
curated_3:'作品の発行日',
curated_4:'',

mp_drops:'最近厳選された作品',
mp_pick:'オルダラブで直接選別し、独占的に提供',
mp_idx:'結果',
mp_1:'見回す',
mp_2:'並べ替え',
mp_3:'新着順',
mp_4:'古い順',
mp_5:'高い順',
mp_6:'安い順',
mp_7:'提案可能',
mp_8:'１次販売作品',

auc_0:'競売',
auc_1:'総 0/5 販売',
auc_2:'総 0/10 販売',
auc_3:'総 1/3 販売',
auc_4:'１個すべて品切り',

ad_info:'アーティスト情報',
ad_name:'',
ad_note:'',
ad_meet:'',
ad_drops:'コレクションリスト',
com_1:'Eメールの認証を進めてください。',
com_2:'Eメールを入力してください。',
com_3:'パスワードを入力してください',
com_4:'会員登録に成功しました。',
com_5:' 会員登録に失敗しました。',
com_6:'正しいアカウントではありません*Eメールアドレス*にお問い合わせください。',
com_7:'Eメール又はパスワードが一致しません。',
com_8:'おめでとうございます！競売に落札されました。\n24時間以内に購入しない場合、競売への参加が制限されます。',

meta_1:'イーサリアムネットワークをsepoliaテストネットワークに変更した後、ご利用ください',
meta_2:'イーサリアムネットワークをメインネットワークに変更した後、ご利用ください。',
meta_3:'メタマスクウォレットの接続を確認してください。',
meta_4:'NFT登録に成功しました。',
meta_5:'NFT登録に失敗しました。',
meta_6:'NFT削除に失敗しました。',
meta_7:'NFT販売中断に成功しました。',
meta_8:'NFT販売中断に失敗しました。',
meta_9:'PCでのみNFT購入が可能です。',
meta_10:'私のNFTは購入できません。.',
meta_11:'NFT購入に失敗しました。',
meta_12:'NFT購入に成功しました。',
meta_13:'NFT購入に失敗しました。',
meta_14:'販売価格を確認してください。',
meta_15:'ロイヤルティーを確認してください。',
meta_16:'NFT発行に失敗しました。',

//자체 토큰 거래 시 문구
meta_approve:'*トークン名*で購入する場合、最初の１回、トークン承認が行われます。',
meta_buy_reject:'同じアイテムが販売中のため、このアイテムは購入できません。',
meta_dsp_no:'*トークン名*トークンが十分ではありません。',
meta_dsp_zero:'保有している*トークン名*トークンがありません。',
meta_again:'もう一度やり直してください。 ',
meta_mo_call:'メタマスクを呼び出します。正常に動作しない場合、pcバージョンをご利用ください。 ',
meta_approve_fail:'Approveに失敗しました。',
//자체 토큰 거래 시 문구
meta_connect:'メタマスクの接続を確認してください。',
mpa_1: '既にウォレットのアドレスが登録されています。',
mpa_2: '既に他の利用者が使用しているウォレットアドレスです。',
mpa_3: 'メタマスクの接続を確認してください。',
mpa_4: '名前を入力してください。',
mpa_5: '情報編集に成功しました。',
mpa_6: '情報編集に失敗しました。 ',
mpa_7: ' プロフィール写真の登録に成功しました。引き続き、他の情報も入力してください。',
mpa_8: '写真容量を確認してください（最大１０ｍｂ）。',
mpa_9: '写真の登録に失敗しました。',
mpa_10: '変更された情報がありません。',

// 리워드 토큰 출금 시 문구 //
wd_notice:'※　注意事項　※　br><br>1. 送金先の*トークン名*ウォレットアドレスの誤記による送金エラーについては、当社では責任を負いません。<br><br>2. 転換申請後、１４日間猶予した後、営業日に登録した送金アドレスに*トークン名*トークンが送金されます。.<br><br>3. １４日間猶予した後、送金日が土、日、公休日の場合は、次の営業日に送金されます。<br><br>4. 転換申請した件については、転換申請の取り消しはできません。 <br><br>5. 8,000*トークン名* Cash 以上出金が可能です。<br><br>',
auc_notice:'※ 注意事項 ※<br><br>1. 競売に落札された場合、Eメールにて落札案内が発送されます。<br><br>2. 競売に落札された場合、２４時間以内に購入しなければ、競売への参加が制限されます。<br>',
offer_notice:'※ 注意事項 ※<br><br>1. 提案の結果はEメールにて落札案内が発送されます。<br><br>2. 提案を受け取った時、販売者がアイテム登録後２４時間以内に購入しない場合、以後提案機能が制限されます。<br>',
alt_address:'正しいウォレットアドレスではありません。\nもう一度確認した後、入力してください。',
alt_address_chk:'ウォレットアドレスを入力してください。',
alt_amount_chk:'出金申請数量を入力してください。',
alt_my_amount_chk:'出金可能数量を超えました。',
alt_zero_chk:'正しい数量を入力してください。',
alt_wd_success:'*トークン名*出金申請が完了しました。',
alt_wd_fail:'*トークン名*出金申請に失敗しました。',
alt_wd_low:'8,000*トークン名* Cashから出金できます。',
alt_reg_already:'既に登録されているEメールです。',
alt_fail:'登録に失敗しました。',

wd_agree:'上記の注意事項をすべて読んでおり、転換申請に同意します。',
wd_1:'出金可能数量',
wd_2:'送金先の*トークン名*ウォレットアドレス',
wd_3:'出金申請数量',
// 리워드 토큰 출금 시 문구 //
close:'閉じる',
mem_del:'会員退会に成功しました。',
mem_del_btn:'会員退会',
auc_flag_no:'競売への参加が制限されたアカウントです。',
support_search:'*サービス名*について知りたいことを検索してみてください。',
support_title:'どのようにお手伝いしましょうか?',
support_notice:'お知らせ',
support_guide:'ガイド',
support_faq:'よくある質問',
support_help:'助けが必要でしょうか？',
support_help_title:'私どもにご連絡いただければ、できるだけ早くご連絡いたします。.',
support_help_btn:'支援センター',
support_more:'もっと見る',


col_items:'アイテム',
col_act:'活動内訳',
col_filter:'フィルター',
col_owners:'所有者',
col_cate:'カテゴリー',
col_status:'状態',
col_price:'価格',
col_filter_btn:'フィルター適用',
col_filter_sel1:'選んでください。',
col_filter_sel2:'選んでください。',
col_filter_status2:'競売',
col_filter_status1:'販売中',

reg_agree:'<a href="#" target="_blank" style="color:blue;">利用約款</a>と <a href="#" target="_blank" style="color:blue;">個人情報取扱方針を</a>確認し、同意します。',
reg_agree_fail:'利用約款と個人情報取扱方針に同意してください。.'
};
